Develop
pow-co/boostpow-api pull request #108
Opened 2023-07-13 20:11 UTC by owenkellogg

2023-07-13 20:17 UTC, owenkellogg commented
Here's an example txid that returns an array with multiple boost jobs: 

https://develop.pow.co/api/v1/boost/jobs/2d4fa08a62e3c538b3a2f0a07a419c30a8e2d7ff699c2a3ef8935b036e412d03

2023-07-14 00:06 UTC, usselman reviewed
I reviewed this for my personal benefit but I will let someone else approve these changes. Looks good to me!

2023-07-14 10:47 UTC, eddiewillers commented
Why does this fail the circleci test?

![Screenshot_20230714_104618_GitHub.jpg](https://github.com/pow-co/boostpow-api/assets/4019818/373829bf-62e4-41c2-8692-d4df18e30f15)

2023-07-14 12:27 UTC, owenkellogg commented
> 

As far as I understand the github ci tests have always failed. It only requires that the circle ci build steps pass, which they do.

2023-07-14 12:42 UTC, eddiewillers commented
I thought @KatrinaAS got the GitHub test to pass a few days ago. I wonder why it would be failing now. Maybe that was a different repo?

2023-07-14 18:07 UTC, ielvisd approved these changes
looks great!

2023-07-14 18:09 UTC, KatrinaAS commented
> Here's an example txid that returns an array with multiple boost jobs:
> 
> https://develop.pow.co/api/v1/boost/jobs/2d4fa08a62e3c538b3a2f0a07a419c30a8e2d7ff699c2a3ef8935b036e412d03

I fixed the tests, so them, failing here means something has been broke

2023-07-14 18:14 UTC, KatrinaAS commented
this is all ignoring the work doing to use the new function added specifically for this in the removedeprication branch so that the function added to bitcoin-js specifically towards this would be used. as Well as removing the use of depreicated functions...

the test is broke btw because of this error:

Error: Cannot find module '../../contracts/personal-interest/artifacts/src/contracts/personalInterest.json'
Require stack:
- /__w/boostpow-api/boostpow-api/src/personal_interests/get_script_hashes.ts

2023-07-14 18:23 UTC, KatrinaAS requested changes
This is a broken pr that isn't actually passing tests, not because tests are broken, I fixed them, but because the code itself is broken.

2023-07-14 18:23 UTC, KatrinaAS commented on src/personal_interests/get_script_hashes.ts
There a reason this file is importing a json file and not a js?

2023-07-14 18:39 UTC, DanielKrawisz commented
This pr uses functions that have been deprecated in boostpow-js. You should use transaction.fromTransaction in boostpow-js to read boost scripts from a tx.

2023-07-14 22:33 UTC, KatrinaAS commented
I have made #109 to fix ONE of the issues with what is going on. note this does not fix the tests AND personal-interest is still broke as scrypt-ts's transpolar can not find the class in contracts/personal-interest/src/contracts/personalInterest.ts

2023-07-15 09:10 UTC, owenkellogg commented
The Circle CI tests pass, so what changes are required and why are they blocking a merge?

2023-07-15 09:11 UTC, owenkellogg commented on src/personal_interests/get_script_hashes.ts
Yes it needs to import a .json file containing the artifact output of an scrypt contract.

2023-07-15 09:42 UTC, owenkellogg commented
> The Circle CI tests pass, so what changes are required and why are they blocking a merge?

Ah I see, the tests weren't passing in the github action, but now they are :D

2023-07-15 09:52 UTC, KatrinaAS approved these changes
All tests pass :D I have some work of my own towards fixing the multiple jobs in one transaction issue but I can fit that into the work done here easily

2023-07-15 09:52 UTC, merged

2023-07-15 09:56 UTC, KatrinaAS commented on src/personal_interests/get_script_hashes.ts
yeah I realised that after buying deep into it, I apologise! It was just confusing when was referencing a missing file. I thought it might have been trying to referencee dist/personalInterest.js